# Generated by Django 3.2 on 2022-03-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('blacklisted', 'Blacklisted'), ('none', 'None')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.book')),
                ('barcode', models.CharField(max_length=20)),
                ('is_referenc_only', models.BooleanField(default=False)),
                ('borrowed', models.DateField()),
                ('due_date', models.DateField()),
                ('price', models.FloatField()),
                ('format', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('audiobook', 'Audiobook'), ('ebook', 'Ebook'), ('newspaper', 'Newspaper'), ('magazine', 'Magazine'), ('journal', 'Journal')], max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('loaned', 'Loaned'), ('lost', 'Lost')], max_length=15)),
                ('date_of_purchase', models.DateField()),
            ],
            bases=('app.book',),
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.account')),
            ],
            bases=('app.account',),
        ),
    ]
